#ifndef CONSTANTES_H
#define CONSTANTES_H

#define TAMANHO_PROMPT 10000
#define TAMANHO_BUFFER_SECOES 1000
#define TAMANHO_MAXIMO_COMANDO 10000
#define QTD_COMANDOS_MAXIMA 5
#define QTD_MAXIMA_ARGUMENTOS 3

#endif
